- name: Install dependencies
  include_tasks:
    file: "install_dependencies.yml"
    apply:
      tags: install
  tags: install

- name: python3, apprise install
  include_tasks:
    file: "install_python_apprise.yml"
    apply:
      tags: install
  tags: install

- name: Create configs
  include_tasks:
    file: "create_configs.yml"
    apply:
      tags: config
  tags: config

- name: Configure cron
  include_tasks:
    file: "configure_cron.yml"
    apply:
      tags: cron
  tags: cron
